### ISSUE TITLE
[FEATURE] Option to pickle the whole strategy

### ISSUE THREAD

**Issue by alexander-soare** [mle-infrastructure/mle-hyperopt#2]
Right now `strategy.save` produces a JSON with the log. Any reason you didn't opt for (or have an option of) pickling the whole strategy? Two motivations for this:

1. Not having to re-init the strategy with all the args/kwargs
2. Not having to loop through tell! SMBO can take quite some time to do this.

**Comment by RobertTLange** [comment]
Sorry for the long wait. I just addressed your request in PR #5. You can now save the state of your strategy as a pickle file as follows:

```python
strategy = RandomSearch(...)
# Explicitly call `save` method
strategy.save("<pkl_filename>.pkl")
# ... or save the strategy with a `tell` call
strategy.tell(configs, scores, save=True, save_fname="<pkl_filename>.pkl")
``` 

You can then reload the log using `strategy.load("<pkl_filename>.pkl")` or providing the path at instantiation. You can now either store the log as easily readable `.json`/`.yaml` or pickle depending on the file extension provided by the desired path! When loading the pickle file, we replace the `__dict__` which stores all writable attributes:

 https://github.com/mle-infrastructure/mle-hyperopt/blob/d72a400ba396874bbfa6549c4ee4a7fba7721354/mle_hyperopt/strategy.py#L266

It will be part of the next release (hopefully coming soon -- I am pretty excited about the new `HalvingSearch`, `HyperbandSearch` and `PBTSearch` implementations). I hope that this addresses your request. Let me know if you have any other recommendations/issues. I will close this for now. Feel free to reopen the issues if something comes up.
